
# HEY! This file is used in the Github integrations tests with CircleCI.
# You should __NEVER__ check credentials into version control. Thanks for reading :)

config:
    send_anonymous_usage_stats: False
    use_colors: True

integration_tests:
  target: snowflake
  outputs:
    redshift:
      type: redshift
      host: "{{ env_var('CI_REDSHIFT_DBT_HOST') }}"
      user: "{{ env_var('CI_REDSHIFT_DBT_USER') }}"
      pass: "{{ env_var('CI_REDSHIFT_DBT_PASS') }}"
      dbname: "{{ env_var('CI_REDSHIFT_DBT_DBNAME') }}"
      port: 5439
      schema: github_integration_tests
      threads: 8
    bigquery:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCLOUD_SERVICE_KEY_PATH') }}"
      project: 'dbt-package-testing'
      schema: github_integration_tests
      threads: 8
    snowflake:
      type: snowflake
      account: "sr68547.ap-southeast-1.snowflakecomputing.com"
      user: "wasan"
      password: "Snowflake28*"
      role: "sysadmin"
      database: "dbt_db"
      warehouse: "dbt_wh"
      schema: github_integration_tests
      threads: 8
